package dev.binarycoders.projecteuler;

/**
 * Even Fibonacci numbers
 * <p>
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Problem002 {

    public static void main(String[] args) {
        final var p002 = new Problem002();

        System.out.printf("Answer: %d", p002.sumOfEvenFibonacci(4_000_000));
    }

    public long sumOfEvenFibonacci(final long number) {
        int first = 1;
        int second = 2;
        long result = 0;

        while (second <= number) {
            if (second % 2 == 0) {
                result += second;
            }

            int tmp = second;
            second = second + first;
            first = tmp;
        }

        return result;
    }
}
